### ISSUE TITLE
Ignore /etc/sysclean.ignore by default

### ISSUE THREAD

**Issue by jturner** [semarie/sysclean#3]
Should sysclean ignore /etc/sysclean.ignore by default? If an ignore rule doesn't catch it sysclean -f will return said file.

**Comment by semarie** [comment]
sysclean has the documented behaviour: it reports a file that isn't installed by default :-)
I agree that it could seems to be a bit odd, but I prefer to make no exception for now, even for sysclean itself.
Thanks for your report.

**Comment by jturner** [comment]
Fair enough. Thanks for the explanation.
