### ISSUE TITLE
/etc/malloc.conf

### ISSUE THREAD

**Issue by renaudallard** [semarie/sysclean#8]
Hello,
Shouldn't /etc/malloc.conf be excluded by default, it's a base OS feature which has its purpose if it has been configured. It's not some random file which shouldn't be there.
What do you think?

**Comment by renaudallard** [comment]
I am wondering if it wouldn't even be better to have it in /etc/changelist
I have sent  a mail to misc@ about that

**Comment by renaudallard** [comment]
Theo is completely against adding malloc.conf in changelist

**Comment by semarie** [comment]
I have discussion about this file with another people. We think that this file should be explicitly added in `/etc/sysclean.ignore`.

If you need such configuration, which affect `malloc(3)` system-wise, you will create such file. No tool will create it automatically for you. So if you want sysclean to not report it, you should add it in ignore file.

Thanks.
