### ISSUE TITLE
Sysclean on rpi zero2 (maybe on rpi4b too?)

### ISSUE THREAD

**Issue by gonzalo-** [semarie/sysclean#9]
Hi Semarie,

It should be sane to add "/etc/firmware/" to the "ignored" list? On my rpi zero2 I got deleted one of the firmware:

`
bwfm0: failed loadfirmware of file brcmfmac43436-sdio.raspberrypi,model-zero-2.bin
`

Cheers.-

**Comment by semarie** [comment]
how do you install this file ? From fw-packages, I can only found `brcmfmac43436-sdio.raspberrypi,model-zero-2-w.bin` (note the `-w` at end) which is from `sysutils/firmware/bwfm`

**Comment by gonzalo-** [comment]
Well. yes, I installed those by hand when rpi-zero-2-w wasn't fully supported... maybe this is because of my "custom" setup...

**Comment by semarie** [comment]
if you installed it by hand, it is expected that sysclean report the file :smile: . you should add the pathname to `/etc/sysclean.ignore`

**Comment by gonzalo-** [comment]
Yes, sorry, I know what happened now, I used the firmware of the zero from github because those are OK for the drivers, but we put them in the port for the zero2 and I should reinstalled those instead of keep the ones from the zero which is "wrong" since is not the right board.

Sorry for the noise!
